name: ci

on:
  pull_request:
    branches:
      - '**'
  workflow_dispatch:

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v5
        with:
          go-version: '1.21.6'
          cache: false
      - name: Run linter
        working-directory: ./
        run: |
          test -z $(gofmt -l .)

  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v5
        with:
          go-version: '1.21.6'
          cache: false
      - name: Run tests
        working-directory: ./
        run: |
          go test -race ./...

  vet:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v5
        with:
          go-version: '1.21.6'
          cache: false
      - name: Run code vetter
        working-directory: ./
        run: |
          go vet ./...
